---
title: "R Notebook"
output: html_notebook
---

```{r load packages}
#install.packages("engsoccerdata")
library(engsoccerdata, quietly = T)
library(tidyverse, quietly = T)
library(lubridate, quietly = T)
library(stringr, quietly = T)
library(rvest, quietly = T)
```

```{r scrape manager data}
site <- 
  read_html("https://en.wikipedia.org/wiki/List_of_Liverpool_F.C._managers")

mtable <- site %>%
  html_nodes("table") %>%
  .[[3]] %>%
  html_table(fill = T) %>%
  as_tibble()

mngrs_clean <- mtable %>%
  select(-Notes) %>%
  filter(row_number() != 1)

# Remove zeros
mngrs_clean$From <- str_sub(mngrs_clean$From, 9, 18)
mngrs_clean$To <- str_sub(mngrs_clean$To , 9, 18)
mngrs_clean$P <- str_sub(mngrs_clean$P, 21)
mngrs_clean$W <- str_sub(mngrs_clean$W, 21)
mngrs_clean$D <- str_sub(mngrs_clean$D, 21)
mngrs_clean$L <- str_sub(mngrs_clean$L, 21)
mngrs_clean$`Win %` <- str_sub(mngrs_clean$`Win %`, 21)

# Convert From and To to dates
mngrs_clean <- mngrs_clean %>%
  mutate(From = as.Date(From)) %>%
  mutate(To = as.Date(To)) %>% 
  mutate(To = ifelse(is.na(To), Sys.Date(), To))

# Convert manager names to last, first format
s <- str_split_fixed(mngrs_clean$Name, " ", n = Inf)
s2 <- str_sub(s[, 2], 1, .5 * nchar(s[, 2]))
newstrings <- cbind(s, s2)
newstrings_names <- paste(newstrings[, 1], newstrings[,"s2"])

mngrs_clean$Name <- newstrings_names
```

```{r create lfc tibble}
# # Plug in missing start data
# mngrs <- mngrs %>%
#   # for Phil Taylor
#   mutate(start = if_else(is.na(start), as.Date("1956-05-05"), start)) %>% 
#   # for George Kay
#   mutate(end   = if_else(is.na(end), as.Date("1951-03-22"), end))

# Subset Liverpool home and away games
lfc <- england %>%
  filter(home == "Liverpool" | visitor == "Liverpool") %>% 
  mutate(Date = as.Date(Date)) %>%
  arrange(Date)

# Create a new column for managers
lfc_mngrs <- lfc %>%
  as_tibble() %>%
  mutate(mngr = "")

# TODO rework this as a function
# Loop to add the rest of the managers
for (i in 1:nrow(mngrs_clean)) {
 lfc_mngrs <- lfc_mngrs %>% 
  mutate(mngr = ifelse(
    Date >= mngrs_clean$From[i] & Date <= mngrs_clean$To[i], 
    mngrs_clean$Name[i], 
    mngr
    ))
}
```

```{r}
# Store records with no manager here
no_mngr <- filter(lfc_mngrs, mngr == "")
```

```{r}
# New goals column and at Anfield column
lfc_mngrs <- lfc_mngrs %>% 
  mutate(
    lfc_goals = 0, 
    lfc_goals = ifelse(home == "Liverpool", hgoal, vgoal), 
    at_anf = "", 
    at_anf = ifelse(home == "Liverpool", "Anfield", "Away")
    )
```

```{r}
ggplot(data = lfc_mngrs, aes(y = lfc_goals, x = goaldif, color = mngr)) + 
  geom_point(alpha = .5, position = "jitter")
```

```{r}
qplot(lfc_goals, data = lfc_mngrs, facets = ~mngr)
```

```{r}
ggplot(data = lfc_mngrs, aes(y = lfc_goals, x = c(1:nrow(lfc_mngrs)), color = mngr)) + 
  geom_point(alpha = .5, position = "jitter")
```

Whether or not Liverpool were playing at Anfield could be associated with the number of goals Liverpool scored.

```{r}
ggplot(data = lfc_mngrs, aes(y = lfc_goals, x = c(1:nrow(lfc_mngrs)), color = at_anf)) + 
  geom_point(alpha = .5, position = "jitter")
```

```{r}
ggplot(data = lfc_mngrs, aes(y = lfc_goals, x = at_anf)) + 
  geom_boxplot()
```

```{r}
mngr_avg <- lfc_mngrs %>% 
  group_by(mngr) %>% 
  summarise(n = n(), goal_avg = mean(lfc_goals)) %>% 
  arrange(desc(goal_avg))
```